name: Upload to AWS S3

on:
  push:
    branches:
      - main
      - dev

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload to S3 Main
      if: github.ref == 'refs/heads/main'
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      run: |
        aws s3 sync . s3://main-devops-portfolio --delete

    - name: Upload to S3 Develop
      if: github.ref == 'refs/heads/dev'
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      run: |
        aws s3 sync . s3://dev-devops-portfolio --delete
