---
  
  name: Devops-Portfolio Deployment

  on:
    push:
      branches:
        - main
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: Deploy static site to S3 bucket
          run: aws s3 sync . s3://devops-portfolio-642 --delete

 #Slack notification Github-Action         
#    notify-slack:
 #     runs-on: ubuntu-latest
  #    needs: build
   #   steps:
    #    - name: Send Slack Notification
     #     uses: slack/actions/send-message@v3
      #    with:
       #     status: ${{ job.status }}
        #    channel_id: <your-slack-channel-id>
         #   text: Workflow ${{ github.workflow }} in repository ${{ github.repository }} has
          #    completed with status ${{ job.status }}
           # env:
            #  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  
